agent_factory_args:
  name: SolverAgent
  model_id: "Qwen/Qwen3.5-9B"
  base_url: "http://localhost:8000/v1"
  api_key: "EMPTY"
  temperature: 0.
  char_limit: 80000

exp_dir: "./results/qwen3.5-9b_shopping"
n_jobs: 1
resume_dir: null
